apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: streaming-data-pvc
  namespace: streaming-server
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard