apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-rtmp-config
  namespace: streaming-server
data:
  nginx.conf: |
    load_module /usr/local/nginx/modules/ngx_rtmp_module.so;
    events {
      worker_connections 1024;
    }
    rtmp {
      server {
        listen 1935;
        chunk_size 4096;
        
        application live {
          live on;
          record off;
          
          hls on;
          hls_path /var/lib/streaming/hls;
          hls_fragment 3;
          hls_playlist_length 60;
          
          dash on;
          dash_path /var/lib/streaming/dash;
        }
      }
    }