apiVersion: v1
kind: Service
metadata:
  name: streaming-server
  namespace: streaming-server
spec:
  type: LoadBalancer
  ports:
  - port: 1935
    targetPort: 1935
    name: rtmp
  - port: 8080
    targetPort: 8080
    name: http
  - port: 8443
    targetPort: 8443
    name: https
  selector:
    app: streaming-server